In [4]:
import pandas as pd

df = pd.read_csv(r'Olist_customers_dataset.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_geolocation_dataset.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_order_items.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_order_payments.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_order_reviews.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_products.csv')
df.head(21)

import pandas as pd
df = pd.read_csv(r'Olist_sellers.csv')
df.head(100)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
95,cda598c48d7c614bc1cad7d8ff6f0010,15137,mirassol,SP
96,d4910f1cdcfdabd48d6b316e395d4a23,9190,santo andre,SP
97,709e16e2b25c7474d980076c6bfc4806,16200,birigui,SP
98,9dc79dd988ac42f4d56c340d7048420a,3569,sao paulo,SP
99,276677b5d08786d5dce7c2149dcce48b,31730,belo horizonte,MG